version: "3.1"

services:
  nodejs:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 3000
    environment: 
      NODE_ENV: production
      VIRTUAL_HOST: lelesweets.co.uk
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: lelesweets.co.uk
      LETSENCRYPT_EMAIL: info@lelesweets.co.uk
    restart: always
    command: ["npm", "run", "serve"]

networks:
  default:
    external:
      name: nginx-proxy