version: "3.1"

services:
  nodejs:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 9000
    environment: 
      NODE_ENV: production
      VIRTUAL_HOST: lelesweets.london
      VIRTUAL_PORT: 9000
      LETSENCRYPT_HOST: lelesweets.london
      LETSENCRYPT_EMAIL: info@lelesweets.london
    restart: always
    command: ["npm", "run", "serve"]

networks:
  default:
    external:
      name: nginx-proxy